name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: debian-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up gcc and make
      run: sudo apt-get update && sudo apt-get install -y build-essential
    - name: make
      run: make
    - name: make test
      run: make test
    - name: Clean up
      run: make clean
